sci-libs/cantera: new fix sphinx doc 'katex_autorenderer.js' SyntaxError
Fix the problem within Cantera 2.4.0 Sphinx Documentation source code:
the `sphinx/html/_static/katex_autorenderer.js` contatains error
> Uncaught /usr/share/cantera/doc/sphinx/html/_static/katex_autorenderer.js:2
> SyntaxError: Unexpected token ,

The problem is solved now by updating dev-python/sphinxcontrib-katex
from 0.2.0 to 0.3.0 version. So the 'sed' command within cantera-2.4.0.ebuild
is not needed anymore.